from pathlib import Path
p=Path('src/worker.js')
s=p.read_text()
start=s.index('function adminPage(user) {')
end=s.index('function injectScript(state, user) {')
replacement=r'''function adminPage(user) {
  const page = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Usuários · Serralheria Net</title><style>body{font-family:Segoe UI,Arial;background:#f4f6f8;margin:0;color:#18212b}main{max-width:900px;margin:auto;padding:24px}.card{background:white;border:1px solid #dfe4e8;border-radius:14px;padding:20px;margin:16px 0}input,select,button{padding:9px;border-radius:8px;border:1px solid #ccd3d8}button{cursor:pointer;background:#1f4e5f;color:white}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.user{display:grid;grid-template-columns:1fr auto auto auto;gap:8px;padding:10px 0;border-bottom:1px solid #eee}@media(max-width:650px){.user{grid-template-columns:1fr}}</style></head><body><main><div class="row"><h1 style="flex:1">Usuários do sistema</h1><a href="/">Voltar ao sistema</a></div><div class="card"><h2>Novo usuário</h2><form id="newf" class="row"><input id="nu" placeholder="usuário" required minlength="3"><input id="np" type="password" placeholder="senha (mín. 8)" required minlength="8"><select id="nr"><option value="employee">Funcionário</option><option value="admin">Administrador</option></select><button>Criar</button></form><div id="msg"></div></div><div class="card"><h2>Cadastrados</h2><div id="list">Carregando…</div></div></main><script>
function h(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
async function loadUsers(){const r=await fetch('/api/users');if(r.status===401){location='/';return}const users=await r.json();let html='';for(const x of users){html+='<div class="user"><strong>'+h(x.username)+'</strong><select data-role="'+x.id+'"><option value="employee" '+(x.role==='employee'?'selected':'')+'>Funcionário</option><option value="admin" '+(x.role==='admin'?'selected':'')+'>Administrador</option></select><label><input type="checkbox" data-active="'+x.id+'" '+(x.active?'checked':'')+'> Ativo</label><button data-save="'+x.id+'">Salvar</button></div>'}document.getElementById('list').innerHTML=html;document.querySelectorAll('[data-save]').forEach(function(b){b.onclick=function(){saveUser(b.getAttribute('data-save'))}})}
async function saveUser(id){const role=document.querySelector('[data-role="'+id+'"]').value,active=document.querySelector('[data-active="'+id+'"]').checked;const p=prompt('Nova senha (deixe em branco para manter):')||'';const body={role:role,active:active};if(p)body.password=p;const r=await fetch('/api/users/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)alert((await r.json()).error);loadUsers()}
document.getElementById('newf').onsubmit=async function(ev){ev.preventDefault();const r=await fetch('/api/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:document.getElementById('nu').value,password:document.getElementById('np').value,role:document.getElementById('nr').value})});document.getElementById('msg').textContent=r.ok?'Usuário criado.':'Não foi possível criar o usuário.';if(r.ok){ev.target.reset();loadUsers()}};loadUsers();
</script></body></html>`;
  return new Response(page, { headers: { 'content-type':'text/html; charset=utf-8','cache-control':'no-store' } });
}

'''
p.write_text(s[:start]+replacement+s[end:])
